# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterUniqueTogether(
            name='boardroom2time2user',
            unique_together=set([('meet_time', 'time', 'boardroom')]),
        ),
    ]
